# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverDtOvrrd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('ser_key', models.BigIntegerField()),
                ('ovrrd_start', models.DateField()),
                ('ovrrd_end', models.DateField()),
                ('ovrrd_cover_dt', models.DateField()),
                ('trans_rcdd', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_spsd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('iss_key', models.BigIntegerField()),
                ('ser_key', models.BigIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('iss_num', models.PositiveSmallIntegerField()),
                ('cover_dt', models.DateField()),
                ('updt_reason', models.CharField(max_length=200)),
                ('trans_rcdd', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_spsd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_nm', models.CharField(max_length=200, unique=True)),
                ('key_value', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('pub_key', models.BigIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('updt_reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=15)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('trans_rcdd', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_spsd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_nm', models.CharField(max_length=200)),
                ('key_value', models.BigIntegerField()),
                ('seq_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('ser_key', models.BigIntegerField()),
                ('pub_key', models.BigIntegerField()),
                ('title', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('updt_reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=15)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('trans_rcdd', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_spsd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('var_key', models.BigIntegerField()),
                ('iss_key', models.BigIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('sub_type', models.CharField(max_length=10)),
                ('cover_dt', models.DateField()),
                ('updt_reason', models.CharField(max_length=200)),
                ('trans_rcdd', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_spsd', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set([('iss_key', 'var_key', 'trans_rcdd')]),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together=set([('pub_key', 'ser_key', 'valid_from', 'trans_rcdd')]),
        ),
        migrations.AlterUniqueTogether(
            name='sequences',
            unique_together=set([('table_nm', 'key_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together=set([('pub_key', 'valid_from', 'trans_rcdd')]),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('ser_key', 'iss_key', 'trans_rcdd')]),
        ),
        migrations.AlterUniqueTogether(
            name='coverdtovrrd',
            unique_together=set([('ser_key', 'ovrrd_start', 'ovrrd_cover_dt', 'trans_rcdd')]),
        ),
    ]
